version: '3.8'

services:
    nginx:
        container_name: grap-king
        image: docker.io/pksos30066/grap-king:least
        ports:
            - '80:8081'
        volumes:
            - ./nginx.conf:/opt/bitnami/nginx/conf/nginx.conf
